import = [
  "github.com/cv21/microgen/pkg/plugins/protobufext"
]

[vars]
trace = true

[[generate]]
plugin = "logging"

  [generate.params]
  path = "service/logging.microgen.go"
  easyjson = true
  took = true
  [generate.params.len]
    FindUsers = ["results"]

[[generate]]
plugin = "logging"

  [generate.params]
  name = "DebugLogging"
  path = "service/debug_logging.microgen.go"
  easyjson = true
  inline = true

[[generate]]
plugin = "opentracing"

  [generate.params]
  path = "service/tracing.microgen.go"
  markerror = true
  logerror = true

[[generate]]
plugin = "recovering"

  [generate.params]
  path = "service/recovering.microgen.go"
  stack = true

[[generate]]
plugin = "go-kit-transport"

  [generate.params]

    [generate.params.exchanges]
    easyjson = true
    style = "camel"

    [generate.params.endpoints]
    latency = true

[[generate]]
plugin = "go-kit-grpc"

  [generate.params]
  protobuf = "github.com/cv21/microgen/examples/usersvc/pb"
  transportpkg = "transport"
  [generate.params.proto]
  gen = true
  package = "devimteam.proto"
  path = "../../pb/api.proto"