import = [
  "github.com/devimteam/microgen/pkg/plugins/protobufext"
]

[vars]
trace = true

[[generate]]
plugin = "logging"

  [generate.params]
  path = "../internal/service/logging.microgen.go"
  easyjson = true
  took = true
  [generate.params.len]
    FindUsers = ["results"]

[[generate]]
plugin = "logging"

  [generate.params]
  name = "DebugLogging"
  path = "../internal/service/debug_logging.microgen.go"
  easyjson = true
  inline = true

[[generate]]
plugin = "opentracing"

  [generate.params]
  path = "../internal/service/tracing.microgen.go"
  markerror = true
  logerror = true

[[generate]]
plugin = "recovering"

  [generate.params]
  path = "../internal/service/recovering.microgen.go"
  stack = true

[[generate]]
plugin = "go-kit-transport"

  [generate.params]

    [generate.params.exchanges]
    path = "../internal/transport/exchanges/exchanges.go"
    easyjson = true
    style = "camel"

    [generate.params.endpoints]
    path = "../internal/transport/endpoints.go"
    latency = true

[[generate]]
plugin = "go-kit-grpc"

  [generate.params]
  protobuf = "github.com/devimteam/microgen/examples/clientsvc/pb"
  transportpkg = "../internal/transport"
  [generate.params.proto]
  gen = true
  package = "devimteam.proto"
  path = "../pb/service.proto"