// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	write_strategy "github.com/recolabs/microgen/generator/write_strategy"
	mock "github.com/stretchr/testify/mock"
)

// Strategy is an autogenerated mock type for the Strategy type
type Strategy struct {
	mock.Mock
}

// Write provides a mock function with given fields: _a0
func (_m *Strategy) Write(_a0 write_strategy.Renderer) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(write_strategy.Renderer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
